### PR TITLE
Uahengo Jr's attempt to completing the beginning Git video series

### PR DESCRIPTION
**Pull request by uahengojr**
Hi,

This PR represents the work I did in completing the Beginning Git video serioes on raywenderlich.com. 

Quite a delightful course. Thanks a Ton!

-UahengoJr

### CODE REVIEW

**Comment by sammyd** [comment]
Congratulations @uahengojr on completing all the challenges for the Beginning Git course.

I'm really glad to hear that you found the course fun—if you weren't already using git for your code, hopefully this has inspired you to do so. Given that we've now launched the next series "Mastering Git", you'll be able to get started straight away!

You can now wear this #GitWarrior badge with pride—and [Tweet](http://ctt.ec/3GUTW) your historic victory!

git-badge


sam

**Comment by uahengojr** [comment]
So, can I like get this merged? Fingers crossed.

**Comment by sammyd** [comment]
I can't merge it, no. If I merge it then nobody else will be able to follow the course in future—because their starting point will be your completed repo. Sorry.

**Comment by uahengojr** [comment]
Aha! Believe it or not, that remark filled a gapping hole in my understanding of the theory behind git. Thanks a ton. Closing PR.

**Pull request closed without merging**
