### PR TITLE
Trying again ;)

### PR DESCRIPTION
**Pull request by Kcm75**
How about now?

Regards Alex

### CODE REVIEW

**Comment by sammyd** [comment]
Hey @Kcm75—congrats on submitting a PR at the end of the git course. I'm hope that you found the course valuable, and that you were able to follow along easily and learn lots.

I noticed that you opened another PR and closed it—was everything OK? Did you have any difficulties?

If you weren't already using git for your code, hopefully this has inspired you to do so. I hope that you enjoy the "Mastering Git" video course as well—you'll soon be able to get git to bend to your will :)

You can now wear this #GitWarrior badge with pride—and [Tweet](http://ctt.ec/3GUTW) your historic victory!

git-badge


sam

**Comment by Kcm75** [comment]
Somehow I forgot to add a reviewer or assignee and couldn't change that after the request was send.  When I make a new pull request I still can't any of both.

The course was very helpful and got me into the "mastering git course" which I am following as we speak ;)

Regards Alex

**Comment by sammyd** [comment]
Ah—ok. This was a mistake on my part—I thought that everybody would be able to add a reviewer when they create the PR. However, it seems that only team members are able to do that. Sorry for it being a little misleading.

Hope you enjoy "mastering git" too—there's some fun stuff in there =)

sam

**Comment by Kcm75** [comment]
No problem, thx for the clarity 🙂

Alex

**Pull request closed without merging**
