### PR TITLE
Clickbait

### PR DESCRIPTION
**Pull request by myihsan**
Hi @sammyd 

Sorry to bother you.
I just tried to make a pull request in my fork but did it like this by mistake.
And I am not able to leave a new comment here so I edit this one for instead.

Thank you for your kind attention.

Ihsan

### CODE REVIEW

**Comment by sammyd** [comment]
Hey @myihsan 

I see you’ve had a go at creating a PR based on this course. Is everything going OK? Having any issues following along with the instructions?

sam

**Comment by myihsan** [comment]
Hi @sammyd 

Sorry to border you like this.
I just tried to make a pull request in my fork but did it like this by mistake.

Thank you for your kind attention!

Ihsan

**Comment by myihsan** [comment]
Hi @sammyd 

Sorry to border you like this.
I just tried to make a pull request in my fork but did it like this by mistake.

Thank you for your kind attention!

Ihsan

**Comment by myihsan** [comment]
Hi @sammyd 

Sorry to bother you.
I just tried to make a pull request in my fork but did it like this by mistake.

Thank you for your kind attention.

Ihsan

**Comment by sammyd** [comment]
Hey @myihsan—you're on the right track—this is a PR from your fork back to the main repo. It doesn't include all the commits form working through the course, but it's a good start.

I see you were having problems with comments—it could just be that you were unlucky—GitHub had a major outage in the last 24 hours, so it could have affected your ability to us it.

Let me know if there's anything you're stuck with.

**Pull request closed without merging**
